spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME:localhost}:${DB_PORT:5432}/${DB_NAME:test}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:magarusik}
    password: ${DB_PASSWORD:1312}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /microservice/api

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

springdoc:
  api-docs:
    path: /docs
  show-actuator: true
  swagger-ui:
    path: /docs-ui.html