spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/test?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:magarusik}
    password: ${DATABASE_PASSWORD:1312}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /microservice/api

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

springdoc:
  api-docs:
    path: /docs
  show-actuator: true
  swagger-ui:
    path: /docs-ui.html