spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/test?createDatabaseIfNotExist=true
    username: magarusik
    password: 1312
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /microservice/api

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html