spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://postgresql:5432/test
    username: magarusik
    password: 1312
    driverClassName: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: /microservice/api/
