--liquibase formatted sql
--changeset magarusik:create-table-posts
create table posts
(
    id        bigint primary key not null generated by default as identity,
    title     varchar            not null unique,
    full_text varchar            not null,
    date      date               not null,
    type_id   bigint             not null
);